[project]
name = "andito"
version = "0.1.0"
description = "Web aggregator for image galleries and collections from several hosting sites"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.2",
    "gallery-dl==1.32.11",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.2.1",
]

[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[tool.hatch]
build.packages = ["src/backend/andito"]
